# Generated by Django 5.2.18 on 2026-10-09 13:01

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='PENDING_VERIFICATION', max_length=24)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
