# Generated by Django 5.2.18 on 2026-10-09 14:22

import apps.core.ids
import apps.evidence.domain.rules
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField()),
                ('organization_id', models.UUIDField()),
                ('evidence_file_id', models.UUIDField()),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=40)),
                ('actor_id', models.UUIDField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'custody_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('EC8A', 'EC8A'), ('EC8B', 'EC8B'), ('EC8C', 'EC8C')], max_length=8)),
                ('object_key', models.CharField(max_length=300, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('mime', models.CharField(max_length=20)),
                ('sha256_client', models.CharField(max_length=64)),
                ('sha256_server', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'PENDING_UPLOAD'), ('UPLOADED', 'UPLOADED'), ('VERIFIED', 'VERIFIED'), ('QUARANTINED', 'QUARANTINED')], default=apps.evidence.domain.rules.EvidenceStatus['PENDING_UPLOAD'], max_length=16)),
                ('quarantine_reason', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.lga')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.pollingunit')),
            ],
            options={
                'db_table': 'evidence_file',
            },
        ),
    ]
