# Generated by Django 5.2.18 on 2026-10-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('geography', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='result_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='results.resultversion'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.ward'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(condition=models.Q(('status', 'PENDING_UPLOAD')), fields=['created_at'], name='evidence_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='evidence_uploader_idx'),
        ),
    ]
