# Generated by Django 5.2.18 on 2026-10-09 13:01

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('scope', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(null=True)),
                ('response_body', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_record',
                'indexes': [models.Index(fields=['expires_at'], name='idempotency_expires_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'scope', 'key'), name='idempotency_unique_key')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='outbox_unpublished_idx')],
            },
        ),
    ]
