# Generated by Django 5.2.18 on 2026-10-09 13:46

import apps.core.ids
import apps.elections.domain.rules
import apps.elections.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('election_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('CONFIGURED', 'CONFIGURED'), ('LOCKED', 'LOCKED'), ('LIVE', 'LIVE'), ('CLOSED', 'CLOSED'), ('RECONCILED', 'RECONCILED')], default=apps.elections.domain.rules.ElectionStatus['DRAFT'], max_length=12)),
                ('count_policy', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified')], default='REPORTED', max_length=10)),
                ('review_enabled', models.BooleanField(default=False)),
                ('polls_open_at', models.DateTimeField(blank=True, null=True)),
                ('polls_close_at', models.DateTimeField(blank=True, null=True)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('config_hash', models.CharField(blank=True, default='', max_length=64)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='organizations.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.state')),
            ],
            options={
                'db_table': 'election',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('office', models.CharField(choices=[('PRESIDENTIAL', 'Presidential'), ('GOVERNORSHIP', 'Governorship'), ('SENATORIAL', 'Senatorial'), ('HOUSE_OF_REPRESENTATIVES', 'House Of Representatives'), ('STATE_ASSEMBLY', 'State Assembly'), ('LGA_CHAIRMAN', 'Lga Chairman'), ('COUNCILLOR', 'Councillor'), ('OTHER', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('jurisdiction_level', models.CharField(choices=[('STATE', 'STATE'), ('LGA', 'LGA'), ('WARD', 'WARD')], max_length=8)),
                ('jurisdiction_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('sheet_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=apps.elections.models.default_sheet_fields, size=None)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='elections.election')),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('party_name', models.CharField(max_length=200)),
                ('party_acronym', models.CharField(max_length=20)),
                ('ballot_order', models.PositiveSmallIntegerField()),
                ('is_own_party', models.BooleanField(default=False)),
                ('config_version', models.PositiveIntegerField()),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='elections.contest')),
            ],
            options={
                'db_table': 'candidate',
                'constraints': [models.UniqueConstraint(fields=('contest', 'ballot_order'), name='candidate_unique_ballot_order'), models.UniqueConstraint(fields=('contest', 'party_acronym'), name='candidate_unique_party'), models.UniqueConstraint(condition=models.Q(('is_own_party', True)), fields=('contest',), name='candidate_one_own_party'), models.CheckConstraint(condition=models.Q(('ballot_order__gte', 1)), name='candidate_ballot_order')],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['organization', 'election_date'], name='election_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='election_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='election',
            constraint=models.CheckConstraint(condition=models.Q(('polls_open_at__isnull', True), ('polls_close_at__isnull', True), ('polls_close_at__gt', models.F('polls_open_at')), _connector='OR'), name='election_polls_window'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('election', 'title'), name='contest_unique_title'),
        ),
    ]
