# Generated by Django 5.2.18 on 2026-10-09 13:01

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('inec_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'geo_state',
            },
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('inec_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgas', to='geography.state')),
            ],
            options={
                'db_table': 'geo_lga',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('inec_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='geography.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.state')),
            ],
            options={
                'db_table': 'geo_ward',
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('inec_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('registered_voters', models.PositiveIntegerField(blank=True, null=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.state')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polling_units', to='geography.ward')),
            ],
            options={
                'db_table': 'geo_polling_unit',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='pu_coordinates_valid')],
            },
        ),
    ]
