# Generated by Django 5.2.18 on 2026-10-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('elections', '0001_initial'),
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='elections.election'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.lga'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='polling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.pollingunit'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.ward'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['election', 'polling_unit'], name='assignment_pu_active_idx'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['agent'], name='assignment_agent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(fields=['election', 'lga'], name='assignment_lga_idx'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(fields=['election', 'ward'], name='assignment_ward_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('election', 'agent', 'polling_unit'), name='assignment_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='agentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='assignment_validity_window'),
        ),
    ]
