# Generated by Django 5.2.18 on 2026-10-09 13:01

import apps.core.ids
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField()),
                ('actor_id', models.UUIDField(null=True)),
                ('actor_role', models.CharField(blank=True, default='', max_length=32)),
                ('organization_id', models.UUIDField(null=True)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('diff', models.JSONField(default=dict)),
                ('batch_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'audit_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditBatch',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveBigIntegerField(unique=True)),
                ('prev_root', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('root', models.CharField(max_length=64)),
                ('event_count', models.PositiveIntegerField()),
                ('first_event_at', models.DateTimeField()),
                ('last_event_at', models.DateTimeField()),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_batch',
            },
        ),
    ]
