# Generated by Django 5.2.18 on 2026-10-09 14:22

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0002_tenant_rls'),
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('raised_by_id', models.UUIDField(blank=True, null=True)),
                ('rule_code', models.CharField(choices=[('ARITHMETIC_VARIANCE', 'ARITHMETIC_VARIANCE'), ('OVER_VOTING', 'OVER_VOTING'), ('DUPLICATE_SOURCE', 'DUPLICATE_SOURCE'), ('VERSION_FORK', 'VERSION_FORK'), ('UNASSIGNED_PU_ATTEMPT', 'UNASSIGNED_PU_ATTEMPT'), ('LATE_SUBMISSION', 'LATE_SUBMISSION'), ('CONFIG_VERSION_MISMATCH', 'CONFIG_VERSION_MISMATCH')], max_length=40)),
                ('rule_version', models.PositiveSmallIntegerField(default=1)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='elections.contest')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='elections.election')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.lga')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.pollingunit')),
            ],
            options={
                'db_table': 'anomaly_flag',
            },
        ),
    ]
