# Generated by Django 5.2.18 on 2026-10-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
        ('geography', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyflag',
            name='result_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='results.resultversion'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.ward'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(condition=models.Q(('status', 'OPEN')), fields=['organization', 'election', 'severity'], name='flag_open_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['election', 'lga'], name='flag_lga_idx'),
        ),
        migrations.AddConstraint(
            model_name='anomalyflag',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN'), ('result_version__isnull', False)), fields=('result_version', 'rule_code'), name='flag_one_open_per_rule'),
        ),
    ]
