# Generated by Django 5.2.18 on 2026-10-09 13:27

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING_VERIFICATION', max_length=24)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
